site_name: Documentation libsegmenter
repo_url: https://github.com/nielsdekoeijer/libsegmenter
theme:
  name: material

nav:
  - Home: index.md
  - API Reference:
      - Segmenter: api/Segmenter.md
      - Segmenter Backends:
          - SegmenterTorch: api/backends/SegmenterTorch.md
          - SegmenterTensorFlow: api/backends/SegmenterTensorFlow.md
          - SegmenterNumpy: api/backends/SegmenterNumpy.md
          - SegmenterOctave: api/backends/SegmenterOctave.md
      - Window: api/Window.md
      - WindowSelector: api/WindowSelector.md
      - Window Implementations:
          - bartlett50: api/windows/bartlett50.md
          - bartlett75: api/windows/bartlett75.md
          - blackman: api/windows/blackman67.md
          - hamming50: api/windows/hamming50.md
          - hamming75: api/windows/hamming75.md
          - hann50: api/windows/hann50.md
          - hann75: api/windows/hann75.md
          - kaiser82: api/windows/kaiser82.md
          - kaiser85: api/windows/kaiser85.md
          - rectangular0: api/windows/rectangular0.md
          - rectangular50: api/windows/rectangular50.md
      - TransformSelector: api/TransformSelector.md
      - Transform Implementations:
          - Spectrogram: api/transforms/Spectrogram.md
          - Spectrogram Backends: 
              - SpectrogramNumpy: api/transforms/Spectrogram/SpectrogramNumpy.md
              - SpectrogramTorch: api/transforms/Spectrogram/SpectrogramTorch.md
              - SpectrogramTensorFlow: api/transforms/Spectrogram/SpectrogramTensorFlow.md
              - SpectrogramOctave: api/transforms/Spectrogram/SpectrogramOctave.md
          - Magnitude: api/transforms/Magnitude.md
          - Magnitude Backends: 
              - MagnitudeNumpy: api/transforms/Magnitude/MagnitudeNumpy.md
              - MagnitudeTorch: api/transforms/Magnitude/MagnitudeTorch.md
              - MagnitudeTensorFlow: api/transforms/Magnitude/MagnitudeTensorFlow.md
              - MagnitudeOctave: api/transforms/Magnitude/MagnitudeOctave.md
          - Phase: api/transforms/Phase.md
          - Phase Backends: 
              - PhaseNumpy: api/transforms/Phase/PhaseNumpy.md
              - PhaseTorch: api/transforms/Phase/PhaseTorch.md
              - PhaseTensorFlow: api/transforms/Phase/PhaseTensorFlow.md
              - PhaseOctave: api/transforms/Phase/PhaseOctave.md
          - BPD: api/transforms/BPD.md
          - BPD Backends: 
              - BPDNumpy: api/transforms/BPD/BPDNumpy.md
              - BPDTorch: api/transforms/BPD/BPDTorch.md
              - BPDTensorFlow: api/transforms/BPD/BPDTensorFlow.md
              - BPDOctave: api/transforms/BPD/BPDOctave.md

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
