site_name: Documentation libsegmenter
repo_url: https://github.com/nielsdekoeijer/libsegmenter
theme:
  name: material

nav:
  - Home: index.md
  - API Reference:
      - Segmenter: api/Segmenter.md
      - Segmenter Implementations:
          - PyTorch: api/backends/SegmenterTorch.md
          - TensorFlow: api/backends/SegmenterTensorFlow.md
          - NumPy: api/backends/SegmenterNumpy.md
      - Window: api/Window.md
      - Window Implementations:
          - bartlett50: api/windows/bartlett50.md
          - bartlett75: api/windows/bartlett75.md
          - blackman: api/windows/blackman.md
          - hamming50: api/windows/hamming50.md
          - hamming75: api/windows/hamming75.md
          - hann50: api/windows/hann50.md
          - hann75: api/windows/hann75.md
          - kaiser82: api/windows/kaiser82.md
          - kaiser85: api/windows/kaiser85.md
          - rectangular0: api/windows/rectangular0.md
          - rectangular50: api/windows/rectangular50.md

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
