# Copyright (c) 2025 Niels de Koeijer, Martin Bo Møller
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

site_name: Documentation libsegmenter
repo_url: https://github.com/nielsdekoeijer/libsegmenter
theme:
  name: material

nav:
  - Home: index.md
  - API Reference:
      - Segmenter: api/Segmenter.md
      - Segmenter Backends:
          - SegmenterTorch: api/backends/SegmenterTorch.md
          - SegmenterTensorFlow: api/backends/SegmenterTensorFlow.md
          - SegmenterNumpy: api/backends/SegmenterNumpy.md
          - SegmenterOctave: api/backends/SegmenterOctave.md
      - Window: api/Window.md
      - WindowSelector: api/WindowSelector.md
      - Window Implementations:
          - bartlett50: api/windows/bartlett50.md
          - bartlett75: api/windows/bartlett75.md
          - blackman: api/windows/blackman67.md
          - hamming50: api/windows/hamming50.md
          - hamming75: api/windows/hamming75.md
          - hann50: api/windows/hann50.md
          - hann75: api/windows/hann75.md
          - kaiser82: api/windows/kaiser82.md
          - kaiser85: api/windows/kaiser85.md
          - rectangular0: api/windows/rectangular0.md
          - rectangular50: api/windows/rectangular50.md
      - TransformSelector: api/TransformSelector.md
      - Transform Implementations:
          - Spectrogram: api/transforms/Spectrogram.md
          - Spectrogram Backends: 
              - SpectrogramNumpy: api/transforms/spectrogram/SpectrogramNumpy.md
              - SpectrogramTorch: api/transforms/spectrogram/SpectrogramTorch.md
              - SpectrogramTensorFlow: api/transforms/spectrogram/SpectrogramTensorFlow.md
              - SpectrogramOctave: api/transforms/spectrogram/SpectrogramOctave.md
          - Magnitude: api/transforms/Magnitude.md
          - Magnitude Backends: 
              - MagnitudeNumpy: api/transforms/magnitude/MagnitudeNumpy.md
              - MagnitudeTorch: api/transforms/magnitude/MagnitudeTorch.md
              - MagnitudeTensorFlow: api/transforms/magnitude/MagnitudeTensorFlow.md
              - MagnitudeOctave: api/transforms/magnitude/MagnitudeOctave.md
          - Phase: api/transforms/Phase.md
          - Phase Backends: 
              - PhaseNumpy: api/transforms/phase/PhaseNumpy.md
              - PhaseTorch: api/transforms/phase/PhaseTorch.md
              - PhaseTensorFlow: api/transforms/phase/PhaseTensorFlow.md
              - PhaseOctave: api/transforms/phase/PhaseOctave.md
          - BPD: api/transforms/BPD.md
          - BPD Backends: 
              - BPDNumpy: api/transforms/bpd/BPDNumpy.md
              - BPDTorch: api/transforms/bpd/BPDTorch.md
              - BPDTensorFlow: api/transforms/bpd/BPDTensorFlow.md
              - BPDOctave: api/transforms/bpd/BPDOctave.md

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
