name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH  # Ensure `uv` is available

      - name: Install Dependencies with uv
        run: |
          uv venv --system --dev  # Use your `--dev` environment
          uv pip install mkdocs mkdocs-material mkdocs-include-markdown-plugin

      - name: Deploy MkDocs
        run: |
          source .venv/bin/activate  # Activate the uv virtual environment
          mkdocs gh-deploy --force

