name: Build and Upload Wheels

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
  
    steps:
    - uses: actions/checkout@v3
      name: Check out repository code
  
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest torch tensorflow numpy
        pip install -e .
      env:
        PYTHONPATH: src 

    - name: Test
      run: pytest
      env:
        PYTHONPATH: src 
  
  build-wheels:
    needs: test
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
      fail-fast: false 
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Set up Python 
      uses: actions/setup-python@v3
  
    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.17.0
  
    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
  
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl

  upload-wheels:
    needs: build-wheels
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/download-artifact@v2
      with:
        path: dist/

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Python version for upload doesn't need to match matrix

    - name: Install twine
      run: python -m pip install twine

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload --repository-url https://upload.pypi.org/legacy/ dist/*/*.whl --verbose --skip-existing
